[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --frozen-lockfile && pnpm --filter api prisma:generate && pnpm --filter api build"

[build.nixpacks]
NIXPACKS_NODE_VERSION = "24"

[deploy]
preDeployCommand = "pnpm --filter api prisma:migrate"
startCommand = "pnpm --filter api start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
